# Generated by Django 4.2.1 on 2023-05-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0003_course_description_course_feature_img_course_techs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "5. Students"},
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("vedio", models.FileField(null=True, upload_to="chapter_videos/")),
                ("techs", models.TextField(null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainlms.course"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Chapters",
            },
        ),
    ]
