# Generated by Django 4.2.1 on 2023-05-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0005_rename_vedio_chapter_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="techs",
            new_name="remarks",
        ),
    ]
