# Generated by Django 4.2.1 on 2023-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0009_studentcourseenrollement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentCourseEnrollement",
            new_name="StudentCourseEnrollment",
        ),
    ]
