# Generated by Django 4.2.1 on 2023-05-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0011_courserating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="detail",
        ),
        migrations.AddField(
            model_name="teacher",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="teacher_profile_imgs/"),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainlms.course",
            ),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainlms.student",
            ),
        ),
    ]
