# Generated by Django 4.2.1 on 2023-05-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0014_alter_courserating_options_studentfavoritecourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(null=True)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainlms.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainlms.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "9. Student Assignments",
            },
        ),
    ]
