# Generated by Django 4.2.1 on 2023-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0015_studentassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassignment",
            name="student_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
