# Generated by Django 4.2.1 on 2023-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0016_studentassignment_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="student_profile_imgs/"),
        ),
    ]
