# Generated by Django 4.2.1 on 2023-05-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0018_notification_alter_student_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name_plural": "10. Notifications"},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notif_text",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_for",
            field=models.CharField(max_length=200, verbose_name="Notification For"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_read_status",
            field=models.BooleanField(
                default=False, verbose_name="Notification Status"
            ),
        ),
    ]
