# Generated by Django 4.2.1 on 2023-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0020_notification_student_notification_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notif_subject",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Notification Subject"
            ),
        ),
    ]
