# Generated by Django 4.2.1 on 2023-05-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0025_attemptquiz_right_ans"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptquiz",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainlms.quiz",
            ),
        ),
    ]
