# Generated by Django 4.2.1 on 2023-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainlms", "0029_student_otp_digit_student_verify_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="login_via_otp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="login_via_otp",
            field=models.BooleanField(default=False),
        ),
    ]
